name: iOS Swift Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "latest-stable"
      - name: Pre-boot Simulator
        # ensures the simulator is ready before the tests start
        run: |
          xcrun simctl boot "iPhone 16 Pro" || true
          xcrun simctl bootstatus "iPhone 16 Pro" -b
      - name: Run swift tests
        working-directory: ./ios-app
        run: |
          xcodebuild test \
            -project Ares_framework.xcodeproj \
            -scheme Ares_framework \
            -destination "platform=iOS Simulator,name=iPhone 16 Pro" \
            -resultBundlePath TestResults.xcresult \
            -test-timeouts-enabled YES \
            -default-test-execution-time-allowance 300 \
            -parallel-testing-enabled NO
            
      - name: Upload Test Results
        #runs even if tests fail
        if: always()
        uses: actions/checkout@v4
        with:
          name: ares-ios-test-results
          path: ios-app/TestResults.xcresult
